### ISSUE TITLE
ajax

### ISSUE THREAD

**Issue by Chriscxa** [NerdmindDE/BigPipe#1]
Hey hi,

I use your Pipe since 5month and your pipe works great.
But now i worked with ajax.
I have in my index.php Pagelets, and \BigPipe\BigPipe::render(); at bottom.
But if i load other php´s via ajax with pagelets I need \BigPipe\BigPipe::render(); on end of php´s too!
But that crashes the Page because  render is used 2 times. 
In < head > are only pageletStaff and the real < head > is under < body >tag.
Also Pagelet is not loaded if got it over ajax. Only after PageRefresh.
Can you help with this issue?
Many thanx

**Comment by Nerdmind** [comment]
Hi, thanks for your feedback and sorry for my late answer (and my bad english), but I'm pretty busy at the time. :)

I assume that you want to load new pages without refreshing the main page via Ajax, right? I have such a solution in a project that uses BigPipe. In this project, I use a "Transport-Frame" to bring the needed HTML content asynchronously into the parent document.

Note: If you call "BigPipe.reset()", you are be able to start a new BigPipe rendering progress if you add new Pagelets with the "onPageletArrive" function.

I can't give you a working solution for this project-specific problem, but if I find a good solution with a understandable example, I will inform you here.

I hope, I could help you! :)

**Comment by Chriscxa** [comment]
nice to hear you.

Yes. This script need a event listener in js for Ajaxresponse.
If response a pagelet: check Ajax-inner-html for pagelets, load his external css & js and show it. 
Thats a missing function. 
Your script is the only one working solution at this moment. All other scripts are too old and doesnt work.
Your script can be great. 

We love your script. Is great. Thanx for your share

**Comment by Chriscxa** [comment]
Hey hi. 

I load for testing a external php with pageletData via Ajax.
All working fine and is loading. But the loaded html.content stay in `<code class="hidden" id="_2secondID"><!-- <section id="red" class="text">Im second</section> --></code>`
`<script></script>`

to load the pagelet via ajax i use:
`$(document).ready(function(){
  $("#click").click(function(){
	BigPipe.reset();
    $("#content").load('home.php');
  });
});`

can you tell whats wrong?

**Comment by Nerdmind** [comment]
Problem solved: https://github.com/NerdmindDE/BigPipe/issues/2
